spring.application.name=36_MicroServices_ServiceDiscovery_App

#Adding Configuration required for Eureka Server
server.port=8761

#Disabling the Registration of this project with Eureka Server
eureka.client.register-with-eureka=false

#Disabling the Discovery operation of this project with Eureka Server
eureka.client.fetch-registry=false